# --- UART & System Support ---
CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_JSON_LIBRARY=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG_PRINTK=y
CONFIG_PRINTK=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_MULTITHREADING=y 
CONFIG_FLASH=y

# --- Gateway & Payload Configurations (Synced with Kconfig) ---
CONFIG_GATEWAY_ID=20
CONFIG_BLE_RECEIVING_PAYLOAD_SIZE=256
CONFIG_CLOUD_UPLOAD_PAYLOAD_SIZE=1024 
CONFIG_UPLOAD_INTERVAL=10
CONFIG_BLE_ADD="CE:BD:BE:AF:BA:11"
CONFIG_AWS_IOT_SAMPLE_JSON_MESSAGE_SIZE_MAX=4096
CONFIG_AWS_IOT_BROKER_HOST_NAME="a1tgjydixa0qkm-ats.iot.us-east-1.amazonaws.com"

# --- Heap & Stacks ---
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=32768

# --- Bluetooth Controller & Long Range (Coded PHY) ---
CONFIG_BT=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_FILTER_ACCEPT_LIST=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_CTLR_ADV_EXT=y
CONFIG_BT_CTLR_PHY_CODED=y

# --- Bluetooth Scanning Buffers ---
CONFIG_BT_BUF_EVT_RX_COUNT=20
CONFIG_BT_PER_ADV_SYNC=y
CONFIG_BT_PER_ADV_SYNC_BUF_SIZE=256
CONFIG_BT_PER_ADV_SYNC_MAX=4
CONFIG_BT_EXT_SCAN_BUF_SIZE=1650
CONFIG_BT_CTLR_SCAN_DATA_LEN_MAX=1650

# --- C Library & File System ---
CONFIG_NEWLIB_LIBC=y
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y

# Automatically format the SD card if it gets corrupted or is blank
CONFIG_FS_FATFS_MOUNT_MKFS=y

# Enable support for SD cards larger than 32GB (exFAT)
CONFIG_FS_FATFS_EXFAT=y

# --- SD Card Hardware Logic ---
CONFIG_SPI=y
CONFIG_SDHC=y
CONFIG_MMC_STACK=y